CREATE DATABASE IF NOT EXISTS g06_agency;

USE g06_agency;

CREATE TABLE IF NOT EXISTS eoi (
  EOInumber INT AUTO_INCREMENT PRIMARY KEY,
  JobReferenceNumber VARCHAR(5) NOT NULL,
  FirstName VARCHAR(20) NOT NULL,
  LastName VARCHAR(20) NOT NULL,
  DOB VARCHAR(10) NOT NULL,
  Gender VARCHAR(20) NOT NULL,
  StreetAddress VARCHAR(40) NOT NULL,
  SuburbTown VARCHAR(40) NOT NULL,
  State VARCHAR(3) NOT NULL,
  Postcode CHAR(4) NOT NULL,
  EmailAddress VARCHAR(100) NOT NULL,
  PhoneNumber VARCHAR(12) NOT NULL,
  Skills TEXT,
  OtherSkills TEXT,
  Status VARCHAR(20) DEFAULT 'New',
  DateSubmitted TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);