<footer>
        <p>&copy; 2026 G06 Creative Digital Media Agency</p>
        <p>
            <a href="https://github.com/grageriann/Group-Project-Assignment/tree/main" target="_blank">GitHub Repository</a> | 
            <a href="https://student-team-fnet57yj.atlassian.net/jira/software/projects/KAN/boards/2" target="_blank">Jira Project</a> | 
            <a href="mailto:106501279@student.swin.edu.au">info@g06agency.com</a>
        </p>
    </footer>
</body>
</html>